auth:
  username: sanou
  password: password  # Change ça en prod !
  database: sanouflix

primary:
  persistence:
    enabled: true
    size: 10Gi
    storageClass: local-path

resources:
  requests:
    memory: 256Mi
    cpu: 250m
  limits:
    memory: 512Mi
    cpu: 500m